# Generated by Django 4.0.2 on 2022-02-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_todo_delete_geeksmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
